### PR TITLE
Temporary release

### PR DESCRIPTION
**Pull request by marcustyphoon**
Not a real pull request.

@gw2princeps, what do you think of doing a single release from this branch? It's just the loading fix and the EoD spec colors without the TS migration work.

### CODE REVIEW

**Comment by gw2princeps** [comment]
So the PR would be this branch and not the other PR? can do for sure, I see merit in fixing this

**Comment by marcustyphoon** [comment]
I assume we want to do the TS migration moving forward, so the other PR is relevant. But if we wanted to have a fixed release out before that project is finished we could release from this branch as e.g. 0.11.11, and then discard it.

**Comment by gw2princeps** [comment]
right, I'm with you then

**Comment by gw2princeps** [comment]
Do you just want to get colord names? Right now the icons are missing

**Comment by gw2princeps** [comment]
no idea what this is or what it does

**Pull request closed without merging**
